### ISSUE TITLE
Custom folder structure

### ISSUE THREAD

**Issue by amviro** [sahusoftcom/eloquent-image-mutator#1]
Hello,
Search engine crawlers are not likely to crawl much deeper folders. It would be great if I could set/pass custom folder structure, for example instead of using lots of sub directories like 
`uploads/user/2015/09/15/37/52/240x180`
I could simply put in 
`uploads/2015/09/240x180/`

or for **User** model I could store images in 
`uploads/user/{userid}/240x180/`

Could you give me some hint how I can achieve it?

Regards

**Comment by lancepioch** [comment]
Modify this portion:

https://github.com/sahusoftcom/eloquent-image-mutator/blob/5d006d7/src/dist/ImageService.php#L105-L108

**Comment by warrenca** [comment]
Is this one better if it's in a config file?

**Comment by sanketsahu** [comment]
I think instead of config file, we should add configurable callback function. Because, config file may not have dynamic names, a callback configuration function makes more sense here.

**Comment by amviro** [comment]
I've a tiny proposal if you are planning to improve folder structure. Instead of creating **multiple folder for each version of the same image**, you could store multiple versions with suffix or create directories with version names and then store images.

For example, instead of 

```
/09/50x50/file1.jpg
/09/100x100/file1.jpg
```

you could do (as wordpress)

```
09/file1-50x50.jpg
09/file1-100x100.jpg
09/file2-50x50.jpg
09/file2-100x100.jpg
```

or version name at the beginning.

```
/50x50/09/file1.jpg
/50x50/09/file2.jpg
/100x100/09/file1.jpg
/100x100/09/file2.jpg
```

Well, its easier said than done. These are just suggestions.

Regards

**Comment by sanketsahu** [comment]
@mrigankmridul What we can do is, have a function in the ServiceProvider which says

```
EloquentImageMutatorServiceProvider::setNamingConfigurator(function($row, $size){

    // Custom naming stuff here
    return $path;

});
```

And this closure function is called every time there is a new file created.

**Comment by mrigankmridul** [comment]
@sanketsahusoft Yes that looks perfect to make upload folder configurable. Thanks

**Comment by warrenca** [comment]
@sanketsahusoft nice one

**Comment by eduardoarandah** [comment]
I support the callback function! for path and title and also different paths for different fields.

I would make the PR but don't really know how. In model construct?

```
class post extends Model
{
    use EloquentImageMutatorTrait;    
    
    protected $image_fields = ['imagefield1','imagefield2'];

    public function __construct(){
        parent::__construct();

        //path for field 1
        $this->setImagePath('imagefield1','post/imagefield1/'.date('Ym'));
        
        //fileName for field 1
        $this->setImageName('imagefield1',str_slug($this->title));

        //path for field 2
        $this->setImagePath('imagefield2','post/imagefield2/');        
    }
...
}


```


using functions?
```

class post extends Model
{
    use EloquentImageMutatorTrait;    
    
    protected $image_fields = ['imagefield1','imagefield2'];

    protected function imagefield1_path(){
        return 'post/imagefield1/'.date('Ym');
    }

    protected function imagefield2_path(){
        return 'post/imagefield2/'.date('Ym');
    }
```
overriding  function getANewFolder() ??
```

	public static function getANewFolder()
	{
	    return  'user/'.date('Y/m/d/i/s');
	}
```
