### ISSUE TITLE
Resized and cropped images rotated

### ISSUE THREAD

**Issue by KalebClark** [sahusoftcom/eloquent-image-mutator#10]
I am using this with a back-end to an IOS native app and the jpegs that are shot on an iPhone have a rotation / orientation flag set in the metadata. When the files are cropped and or rotated in the mutator, it strips the metadata from the file and the image gets rotated 90 deg.

Have you encountered this before? 

I have some ideas to fix it, just wondering if you could tell me a good entry point into the mutator just after upload and before any of the image processing happens. I would be glad to implement the fix and submit a pull request.

Thanks again,
-Kaleb

**Comment by KalebClark** [comment]
I've got a fix implemented. Detects the rotation based on the exif metadata, and then does the correction in the resize method just before save. I'll test it in our app for a few days and submit a pull request if all goes well.

Thanks,
-Kaleb

**Comment by sanketsahu** [comment]
Thanks a lot Kaleb!

That would definitely help. We're a bit busy at the moment to work on this. A pull request would be great.

Best,
Sanket
