### ISSUE TITLE
For Laravel 5.0 ?

### ISSUE THREAD

**Issue by elsifi** [sahusoftcom/eloquent-image-mutator#11]
Is this compatible with Laravel 5.0?
And what to add to composer if so?

**Comment by mrigankmridul** [comment]
@ElSifi Yes it is.
Run this command in your project root 

```
composer require sahusoftcom/eloquent-image-mutator
```

OR 

Just add the line below to composer.json require section and run composer install

```
"sahusoftcom/eloquent-image-mutator": "v2.1.6"
```

**Comment by elsifi** [comment]
Thanks a alot.

**Comment by mrigankmridul** [comment]
Welcome :+1:
