### ISSUE TITLE
url properties null

### ISSUE THREAD

**Issue by mushu8** [sahusoftcom/eloquent-image-mutator#12]
i'm building a blog with articles and one image by article (property img_top)
i have a create form with text fields and a dropzone.js preview image uploader.
when an image is uploaded via the dropzone plugin, the file is temporarily stored in public/img/tmp/
and the path is returned to the form into an input hidden (name ="img_top" value="/img/tmp/1452170570-download.jpeg")
So when i submit the form the controller receive that path : 

```
public function store(ArticlesRequest $request) {

        if ($request->has('img_top'))
        {
            $request->merge(['img_top' => public_path() . $request->input('img_top')]);
        }

        $article = new Article($request->all());

        \Auth::user()->articles()->save($article);

        return redirect('articles');
    }
```

but in the index page the property $article->img_top->profile->url is null

**Comment by mrigankmridul** [comment]
@mushu8 
As you have mentioned the value is /img/tmp/1452170570-download.jpeg. The mutator wouldn't be able to download the image as its not the full path.You need to provide a image file or a complete url/path. IF you are using a public path on your local system the folder where the image is should have all permissions for the mutator to access.

For example if it was on github.com the path would be `https://github.com/img/tmp/1452170570-download.jpeg` OR Locally `/Users/mrigank/Sites/projects/eloquent-image-mutator/public/img/tmp/1452170570-download.jpeg` with all permissions.

**Comment by mushu8** [comment]
@mrigankmridul 
in my example you can see some code from the controller where i concatenate :
public_path() with $request->input('img_top') which contains the relative path.
to be sure i logged it again and here is one example :

Same example as in the question with dd() call added :

```
public function store(ArticlesRequest $request) {

        if ($request->has('img_top'))
        {
            $request->merge(['img_top' => public_path() . $request->input('img_top')]);
        }

        dd($request->input('img_top'));

        $article = new Article($request->all());

        \Auth::user()->articles()->save($article);

        return redirect('articles');
    }
```

 this code outputs : '/home/vagrant/app/public/img/tmp/1452345984-download.jpeg'

**Comment by mushu8** [comment]
my symbolic link is like this :

```
~$ ls -l app/public/uploads
lrwxrwxrwx 1 501 dialout 23 Jan  7 12:59 appkin/public/uploads -> ../storage/app/uploads//
```

with config file :

```
return array(
    'library'     => 'gd',
    'upload_dir'  => 'uploads',
    'assets_upload_path' => 'storage/app/uploads',
    'quality'     => 85,
    'dimensions'  => [
        ['50','50',true, 85, 'thumbnail'],
        ['160','120',false, 85, 'xsmall'],
        ['240','180',false, 85, 'small'],
        ['300','300',true, 85, 'profile'],
        ['640','480',false, 85, 'medium'],
        ['800','600',false, 85, 'large']
    ]
);
```

and when the $article->top_img is assigned, dump shows this :

```
"img_top" => "{"thumbnail":{"url":"\/uploads\/user\/2016\/01\/09\/46\/02\/50x50_crop\/YI1MyFIL4NXFCMMI.jpeg","height":50,"width":50},"xsmall":{"url":"\/uploads\/user\/2016\/01\/09\/46\/02\/160x120\/YI1MyFIL4NXFCMMI.jpeg","height":80,"width":160},"small":{"url":"\/uploads\/user\/2016\/01\/09\/46\/02\/240x180\/YI1MyFIL4NXFCMMI.jpeg","height":120,"width":240},"profile":{"url":"\/uploads\/user\/2016\/01\/09\/46\/02\/300x300_crop\/YI1MyFIL4NXFCMMI.jpeg","height":200,"width":300},"medium":{"url":"\/uploads\/user\/2016\/01\/09\/46\/02\/640x480\/YI1MyFIL4NXFCMMI.jpeg","height":200,"width":400},"large":{"url":"\/uploads\/user\/2016\/01\/09\/46\/02\/800x600\/YI1MyFIL4NXFCMMI.jpeg","height":200,"width":400},"original":{"url":"\/uploads\/user\/2016\/01\/09\/46\/02\/YI1MyFIL4NXFCMMI.jpeg","height":null,"width":null}}"
```

**Comment by mushu8** [comment]
debugging the lib, i understood that strangly only 255 caracters of the json was saved in the db…
so i changed my top_image from string to text in my migration as sayed in your doc (perhaps you could write this in bold)
thanks anyway :+1:

**Comment by mrigankmridul** [comment]
@mushu8 LOL that was the first point in `How to use` section. No worries the issue is resolved now, that is what matters. :+1: :smile:
