### ISSUE TITLE
Resource from URL

### ISSUE THREAD

**Issue by endytc** [sahusoftcom/eloquent-image-mutator#22]
I'm trying use this fiture,
` $user->profile_picture = https://scontent.fcgk4-1.fna.fbcdn.net/v/t1.0-9/15823332_10154707396136071_625452905041554984_n.jpg?_nc_eui2=v1%3AAeGl0ssib7xKRZXWhhC6NByxuozhJDoY-1kK1ndmSJqDeo7LhdRaLOzPQkY6p_GUC11MTS8LF38BzpnUP-L2sE2WjOxgJNCcSZso1xLPq3qG0Q&oh=f9ccbb5dcaabf4a92675f50966ed2bf7&oe=5921F0C2`
`$user->save();`
but when I want to getting the image. image not found, and I try check this url, with 
` $user->profile_picture`
I found 
`http://127.0.0.1/reseller2/public/uploads/user/2017/01/01/08/22/50x50_crop/1gJV1b9NkrSf3W6U.jpg?_nc_eui2=v1%3AAeGl0ssib7xKRZXWhhC6NByxuozhJDoY-1kK1ndmSJqDeo7LhdRaLOzPQkY6p_GUC11MTS8LF38BzpnUP-L2sE2WjOxgJNCcSZso1xLPq3qG0Q&oh=f9ccbb5dcaabf4a92675f50966ed2bf7&oe=5921F0C2`

why GET parameter be included in the file name?

**Comment by sanketsahusoft** [comment]
@endytc It's because of the header redirect in the URL which you're trying to save.

**Comment by sanketsahu** [comment]
That's happening because the script checks the extension by exploding the string by `.` and taking the last part.

I don't think it would create any problem.
