### ISSUE TITLE
Images being uploaded, but the model does not have the correct path

### ISSUE THREAD

**Issue by coryfail** [sahusoftcom/eloquent-image-mutator#29]
The model is set up correctly and I am saving the image like so

        $photo = new Photo;
        $photo->file_path = $request->file('image_file');
        $photo->save();

The issue is when I call the model in my view {{$photo->file_path->medium->url}} it only returns the default image that I set in image.php

The image is being uploaded correctly.. it has been uploaded and made into smaller sizes... it is just not being saved to the model itself since all sizes shows the default image.

**Comment by coryfail** [comment]
I just saw in other issues that the datatype needs to be text and not string, I'll see if that fixes the problem.

**Comment by mrigankmridul** [comment]
Yes surely that will fix it @fyroc , the datatype needs to be text as the json string is long. Let me know if it doesn't work, closing it for now. Cheers!

**Comment by coryfail** [comment]
Oddly enough it did not fix it. I see the correct data in the database but not the model. Does the model need to be refreshed?

**Comment by coryfail** [comment]
@mrigankmridul This hasn't been resolved, FYI.

**Comment by mrigankmridul** [comment]
The database column type should be text and file should be uploaded to the specified folders(which is happening). @fyroc are you getting any error ? I don't see any other issue here.

**Comment by coryfail** [comment]
No error... it's just when I call the model this is my output

```
ImageFieldLocal {#323 ▼
  +"thumbnail": ImageFile {#324 ▼
    +url: "http://placehold.it/150x150"
    +height: 150
    +width: 150
  }
  +"xsmall": ImageFile {#325 ▼
    +url: "http://placehold.it/150x150"
    +height: 150
    +width: 150
  }
  +"small": ImageFile {#326 ▼
    +url: "http://placehold.it/150x150"
    +height: 150
    +width: 150
  }
  +"profile": ImageFile {#327 ▼
    +url: "http://placehold.it/150x150"
    +height: 150
    +width: 150
  }
  +"medium": ImageFile {#328 ▼
    +url: "http://placehold.it/150x150"
    +height: 150
    +width: 150
  }
  +"large": ImageFile {#329 ▼
    +url: "http://placehold.it/150x150"
    +height: 150
    +width: 150
  }
  +"orignal": ImageFile {#330 ▼
    +url: "http://placehold.it/150x150"
    +height: 150
    +width: 150
  }
  +"original": ImageFile {#331 ▼
    +url: "http://placehold.it/150x150"
    +height: 150
    +width: 150
  }
}
```

when it is supposed to be my images

**Comment by coryfail** [comment]
@mrigankmridul am I missing something with my model?

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use SahusoftCom\EloquentImageMutator\EloquentImageMutatorTrait;

class Photo extends Model
{
    use EloquentImageMutatorTrait;

    /**
    * The photo fields should be listed here.
    *
    * @var array
    */

    protected $image_fields = ['file_path'];

    protected $fillable = ['file_path'];

    protected $hidden = [];
```

**Comment by mrigankmridul** [comment]
@fyroc Looks good to me. Try deleting the record from db and upload again.
